import { FormEvent, useEffect, useMemo, useState } from 'react';
import { supabase } from './lib/supabase';
import { Activity, ArrowUpRight, CalendarDays, Check, ChevronDown, Clock3, Coffee, LayoutDashboard, Menu, MoreHorizontal, Plus, Search, Settings2, ShieldCheck, Users, X } from 'lucide-react';

type Department = { id: string; name: string; description: string; color: string };
type Employee = { id: string; first_name: string; last_name: string; email: string; phone: string; job_title: string; department_id: string | null; employment_type: string; status: string; start_date: string; location: string; salary: number; avatar_color: string; departments?: { name: string; color: string } | null };
type Attendance = { id: string; employee_id: string; work_date: string; check_in: string | null; check_out: string | null; status: string; employees?: { first_name: string; last_name: string; job_title: string } | null };
type LeaveRequest = { id: string; employee_id: string; leave_type: string; start_date: string; end_date: string; reason: string; status: string; employees?: { first_name: string; last_name: string } | null };
type View = 'Overview' | 'Employees' | 'Attendance' | 'Time off' | 'Departments';

const initials = (employee: Pick<Employee, 'first_name' | 'last_name'>) => `${employee.first_name[0]}${employee.last_name[0]}`;
const formatDate = (value: string) => new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(`${value}T00:00:00`));
const formatTime = (value: string | null) => value ? new Intl.DateTimeFormat('en-US', { hour: 'numeric', minute: '2-digit' }).format(new Date(value)) : '—';

function App() {
  const [view, setView] = useState<View>('Overview');
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [departments, setDepartments] = useState<Department[]>([]);
  const [attendance, setAttendance] = useState<Attendance[]>([]);
  const [leaveRequests, setLeaveRequests] = useState<LeaveRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [query, setQuery] = useState('');
  const [showEmployeeForm, setShowEmployeeForm] = useState(false);
  const [showLeaveForm, setShowLeaveForm] = useState(false);
  const [toast, setToast] = useState('');
  const [mobileNav, setMobileNav] = useState(false);

  const loadData = async () => {
    setLoading(true);
    const [employeeResult, departmentResult, attendanceResult, leaveResult] = await Promise.all([
      supabase.from('employees').select('*, departments(name, color)').order('created_at', { ascending: false }),
      supabase.from('departments').select('*').order('name'),
      supabase.from('attendance').select('*, employees(first_name, last_name, job_title)').order('work_date', { ascending: false }),
      supabase.from('leave_requests').select('*, employees(first_name, last_name)').order('created_at', { ascending: false }),
    ]);
    if (employeeResult.error || departmentResult.error || attendanceResult.error || leaveResult.error) {
      setToast('Could not load workspace data. Please refresh and try again.');
    } else {
      setEmployees(employeeResult.data ?? []);
      setDepartments(departmentResult.data ?? []);
      setAttendance(attendanceResult.data ?? []);
      setLeaveRequests(leaveResult.data ?? []);
    }
    setLoading(false);
  };

  useEffect(() => { void loadData(); }, []);
  useEffect(() => { if (!toast) return; const timeout = window.setTimeout(() => setToast(''), 3200); return () => window.clearTimeout(timeout); }, [toast]);

  const activeEmployees = employees.filter((employee) => employee.status === 'Active');
  const presentToday = attendance.filter((record) => record.work_date === new Date().toISOString().slice(0, 10) && record.status === 'Present').length;
  const pendingLeave = leaveRequests.filter((request) => request.status === 'Pending');
  const filteredEmployees = employees.filter((employee) => `${employee.first_name} ${employee.last_name} ${employee.job_title} ${employee.departments?.name ?? ''}`.toLowerCase().includes(query.toLowerCase()));

  const updateLeave = async (id: string, status: 'Approved' | 'Declined') => {
    const { error } = await supabase.from('leave_requests').update({ status }).eq('id', id);
    if (error) setToast('That request could not be updated.'); else { setLeaveRequests((items) => items.map((item) => item.id === id ? { ...item, status } : item)); setToast(`Request ${status.toLowerCase()}.`); }
  };

  const navItems: { label: View; icon: typeof LayoutDashboard }[] = [
    { label: 'Overview', icon: LayoutDashboard }, { label: 'Employees', icon: Users }, { label: 'Attendance', icon: Clock3 }, { label: 'Time off', icon: CalendarDays }, { label: 'Departments', icon: ShieldCheck },
  ];

  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? 'mobile-open' : ''}`}>
      <div className="brand"><div className="brand-mark">P</div><div><strong>people<span>os</span></strong><small>HR workspace</small></div><button className="mobile-close" onClick={() => setMobileNav(false)}><X size={18} /></button></div>
      <div className="workspace-switcher"><div className="workspace-icon">A</div><div><strong>Acme Inc.</strong><small>Workspace</small></div><ChevronDown size={15} /></div>
      <nav>{navItems.map(({ label, icon: Icon }) => <button key={label} className={view === label ? 'active' : ''} onClick={() => { setView(label); setMobileNav(false); }}><Icon size={18} /><span>{label}</span>{label === 'Time off' && pendingLeave.length > 0 && <b>{pendingLeave.length}</b>}</button>)}</nav>
      <div className="sidebar-bottom"><button><Settings2 size={18} /><span>Settings</span></button><div className="user-card"><div className="avatar avatar-sand">JD</div><div><strong>Jamie Davis</strong><small>HR manager</small></div><MoreHorizontal size={17} /></div></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><button className="menu-button" onClick={() => setMobileNav(true)}><Menu size={21} /></button><div className="breadcrumbs"><span>Workspace</span><span>/</span><strong>{view}</strong></div><div className="top-actions"><div className="top-search"><Search size={16} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search anything..." /></div><button className="icon-button"><Activity size={18} /></button><button className="profile-button"><div className="avatar avatar-sand">JD</div><ChevronDown size={15} /></button></div></header>
      <div className="page-wrap">
        {view === 'Overview' && <Overview employees={employees} attendance={attendance} leaveRequests={leaveRequests} activeEmployees={activeEmployees} presentToday={presentToday} pendingLeave={pendingLeave} onAddEmployee={() => setShowEmployeeForm(true)} onViewTimeOff={() => setView('Time off')} onUpdateLeave={updateLeave} loading={loading} />}
        {view === 'Employees' && <Employees employees={filteredEmployees} departments={departments} onAdd={() => setShowEmployeeForm(true)} loading={loading} />}
        {view === 'Attendance' && <AttendanceView records={attendance} loading={loading} />}
        {view === 'Time off' && <TimeOff requests={leaveRequests} onAdd={() => setShowLeaveForm(true)} onUpdate={updateLeave} loading={loading} />}
        {view === 'Departments' && <Departments departments={departments} employees={employees} loading={loading} />}
      </div>
    </main>
    {showEmployeeForm && <EmployeeForm departments={departments} onClose={() => setShowEmployeeForm(false)} onSaved={() => { setShowEmployeeForm(false); void loadData(); setToast('Employee added to the directory.'); }} />}
    {showLeaveForm && <LeaveForm employees={employees} onClose={() => setShowLeaveForm(false)} onSaved={() => { setShowLeaveForm(false); void loadData(); setToast('Time-off request submitted.'); }} />}
    {toast && <div className="toast"><Check size={17} />{toast}</div>}
  </div>;
}

function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action}</div>; }
function StatCard({ icon: Icon, label, value, detail, tone }: { icon: typeof Users; label: string; value: string | number; detail: string; tone: string }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={19} /></div><div className="stat-copy"><span>{label}</span><strong>{value}</strong><small>{detail}</small></div><ArrowUpRight size={16} className="stat-arrow" /></div>; }

function Overview({ employees, attendance, leaveRequests, activeEmployees, presentToday, pendingLeave, onAddEmployee, onViewTimeOff, onUpdateLeave, loading }: { employees: Employee[]; attendance: Attendance[]; leaveRequests: LeaveRequest[]; activeEmployees: Employee[]; presentToday: number; pendingLeave: LeaveRequest[]; onAddEmployee: () => void; onViewTimeOff: () => void; onUpdateLeave: (id: string, status: 'Approved' | 'Declined') => void; loading: boolean }) {
  const latestEmployees = employees.slice(0, 5); const recentRequests = leaveRequests.slice(0, 4); const dayRecords = attendance.filter((record) => record.work_date === new Date().toISOString().slice(0, 10));
  return <><PageHeader eyebrow="Tuesday, October 24, 2024" title="Good morning, Jamie" description="Here’s what’s happening across your people today." action={<button className="primary-button" onClick={onAddEmployee}><Plus size={17} /> Add employee</button>} />
    <div className="stat-grid"><StatCard icon={Users} label="Total employees" value={activeEmployees.length} detail="Active in workspace" tone="teal" /><StatCard icon={Clock3} label="Present today" value={presentToday || '—'} detail={`${dayRecords.length ? `${dayRecords.length} check-ins recorded` : 'No check-ins yet'}`} tone="blue" /><StatCard icon={CalendarDays} label="Time off requests" value={pendingLeave.length} detail="Waiting for review" tone="orange" /><StatCard icon={Coffee} label="On leave today" value={leaveRequests.filter((request) => request.status === 'Approved').length || '—'} detail="Approved requests" tone="sand" /></div>
    <div className="content-grid"><section className="panel team-panel"><div className="panel-heading"><div><h2>Recent employees</h2><p>Your newest team members</p></div><a onClick={() => {}} href="#employees">View all <ArrowUpRight size={14} /></a></div>{loading ? <Loading /> : latestEmployees.length === 0 ? <Empty title="No employees yet" text="Add your first employee to start building the directory." /> : <div className="employee-list">{latestEmployees.map((employee) => <div className="employee-row" key={employee.id}><div className="avatar" style={{ background: employee.avatar_color }}>{initials(employee)}</div><div className="employee-info"><strong>{employee.first_name} {employee.last_name}</strong><span>{employee.job_title}</span></div><span className="department-pill" style={{ color: employee.departments?.color }}>{employee.departments?.name ?? 'Unassigned'}</span><span className="status-dot"><i />{employee.status}</span><MoreHorizontal size={17} className="muted-icon" /></div>)}</div>}</section>
      <section className="panel request-panel"><div className="panel-heading"><div><h2>Needs your attention</h2><p>Requests waiting for review</p></div><button className="text-button" onClick={onViewTimeOff}>See all <ArrowUpRight size={14} /></button></div>{recentRequests.length === 0 ? <Empty title="All caught up" text="There are no requests waiting for your review." /> : <div className="request-list">{recentRequests.map((request) => <div className="request-row" key={request.id}><div className="avatar avatar-rose">{request.employees ? initials(request.employees as Employee) : '?'}</div><div className="request-info"><strong>{request.employees?.first_name} {request.employees?.last_name}</strong><span>{request.leave_type} · {formatDate(request.start_date)}</span></div>{request.status === 'Pending' ? <div className="request-actions"><button className="approve" onClick={() => onUpdateLeave(request.id, 'Approved')} aria-label="Approve"><Check size={15} /></button><button className="decline" onClick={() => onUpdateLeave(request.id, 'Declined')} aria-label="Decline"><X size={15} /></button></div> : <span className={`status-label ${request.status.toLowerCase()}`}>{request.status}</span>}</div>)}</div>}</section>
    </div>
    <section className="panel quick-panel"><div className="panel-heading"><div><h2>Quick overview</h2><p>A snapshot of your team composition</p></div></div><div className="overview-bars"><div><div className="bar-label"><span>Full-time employees</span><strong>{activeEmployees.filter((employee) => employee.employment_type === 'Full-time').length}</strong></div><div className="bar-track"><i style={{ width: `${activeEmployees.length ? Math.max(12, activeEmployees.filter((employee) => employee.employment_type === 'Full-time').length / activeEmployees.length * 100) : 0}%` }} /></div></div><div><div className="bar-label"><span>Remote employees</span><strong>{activeEmployees.filter((employee) => employee.location === 'Remote').length}</strong></div><div className="bar-track"><i className="blue-bar" style={{ width: `${activeEmployees.length ? Math.max(12, activeEmployees.filter((employee) => employee.location === 'Remote').length / activeEmployees.length * 100) : 0}%` }} /></div></div><div><div className="bar-label"><span>Departments</span><strong>{new Set(employees.map((employee) => employee.department_id)).size || 0}</strong></div><div className="bar-track"><i className="orange-bar" style={{ width: `${Math.min(100, new Set(employees.map((employee) => employee.department_id)).size * 18)}%` }} /></div></div></div></section>
  </>;
}

function Employees({ employees, departments, onAdd, loading }: { employees: Employee[]; departments: Department[]; onAdd: () => void; loading: boolean }) { return <><PageHeader eyebrow="People directory" title="Employees" description="Keep your team information organized and up to date." action={<button className="primary-button" onClick={onAdd}><Plus size={17} /> Add employee</button>} /><div className="toolbar"><div className="filter-search"><Search size={17} /><input placeholder="Search employees" /></div><button className="filter-button">All departments <ChevronDown size={15} /></button><button className="filter-button">Active <ChevronDown size={15} /></button></div><section className="panel table-panel">{loading ? <Loading /> : employees.length === 0 ? <Empty title="No employees found" text="Try a different search or add a new employee." /> : <div className="table-wrap"><table><thead><tr><th>Employee</th><th>Department</th><th>Role</th><th>Location</th><th>Status</th><th /></tr></thead><tbody>{employees.map((employee) => <tr key={employee.id}><td><div className="table-person"><div className="avatar" style={{ background: employee.avatar_color }}>{initials(employee)}</div><div><strong>{employee.first_name} {employee.last_name}</strong><span>{employee.email}</span></div></div></td><td><span className="department-pill" style={{ color: employee.departments?.color }}>{employee.departments?.name ?? 'Unassigned'}</span></td><td>{employee.job_title}</td><td>{employee.location}</td><td><span className="status-dot"><i />{employee.status}</span></td><td><MoreHorizontal size={18} className="muted-icon" /></td></tr>)}</tbody></table></div>}</section><div className="directory-note"><ShieldCheck size={17} /><span>{departments.length} departments are set up for your workspace.</span></div></>; }
function AttendanceView({ records, loading }: { records: Attendance[]; loading: boolean }) { return <><PageHeader eyebrow="Daily tracking" title="Attendance" description="See who is in, away, or working remotely." action={<button className="filter-button"><CalendarDays size={16} /> Today <ChevronDown size={15} /></button>} /><div className="stat-grid attendance-stats"><StatCard icon={Check} label="Present" value={records.filter((record) => record.status === 'Present').length} detail="Logged today" tone="teal" /><StatCard icon={Clock3} label="Late arrivals" value={records.filter((record) => record.status === 'Late').length} detail="Needs a check-in" tone="orange" /><StatCard icon={Coffee} label="Away" value={records.filter((record) => record.status === 'Away').length} detail="Out of office" tone="sand" /></div><section className="panel table-panel">{loading ? <Loading /> : records.length === 0 ? <Empty title="No attendance recorded" text="Attendance records will appear here once your team checks in." /> : <div className="table-wrap"><table><thead><tr><th>Employee</th><th>Date</th><th>Check in</th><th>Check out</th><th>Status</th></tr></thead><tbody>{records.map((record) => <tr key={record.id}><td><div className="table-person"><div className="avatar avatar-mint">{record.employees ? initials(record.employees as Employee) : '?'}</div><div><strong>{record.employees?.first_name} {record.employees?.last_name}</strong><span>{record.employees?.job_title}</span></div></div></td><td>{formatDate(record.work_date)}</td><td>{formatTime(record.check_in)}</td><td>{formatTime(record.check_out)}</td><td><span className={`status-label ${record.status.toLowerCase()}`}>{record.status}</span></td></tr>)}</tbody></table></div>}</section></>; }
function TimeOff({ requests, onAdd, onUpdate, loading }: { requests: LeaveRequest[]; onAdd: () => void; onUpdate: (id: string, status: 'Approved' | 'Declined') => void; loading: boolean }) { return <><PageHeader eyebrow="Leave management" title="Time off" description="Review and manage your team's upcoming time away." action={<button className="primary-button" onClick={onAdd}><Plus size={17} /> New request</button>} /><div className="tabs"><button className="selected">All requests <b>{requests.length}</b></button><button>Pending <b>{requests.filter((request) => request.status === 'Pending').length}</b></button><button>Approved</button></div><section className="panel table-panel">{loading ? <Loading /> : requests.length === 0 ? <Empty title="No time-off requests" text="Your team's leave requests will show up here." /> : <div className="table-wrap"><table><thead><tr><th>Employee</th><th>Type</th><th>Dates</th><th>Reason</th><th>Status</th><th /></tr></thead><tbody>{requests.map((request) => <tr key={request.id}><td><div className="table-person"><div className="avatar avatar-rose">{request.employees ? initials(request.employees as Employee) : '?'}</div><strong>{request.employees?.first_name} {request.employees?.last_name}</strong></div></td><td>{request.leave_type}</td><td>{formatDate(request.start_date)} – {formatDate(request.end_date)}</td><td className="reason-cell">{request.reason || '—'}</td><td>{request.status === 'Pending' ? <div className="inline-actions"><button className="approve" onClick={() => onUpdate(request.id, 'Approved')}><Check size={15} /> Approve</button><button className="decline" onClick={() => onUpdate(request.id, 'Declined')}><X size={15} /></button></div> : <span className={`status-label ${request.status.toLowerCase()}`}>{request.status}</span>}</td><td><MoreHorizontal size={18} className="muted-icon" /></td></tr>)}</tbody></table></div>}</section></>; }
function Departments({ departments, employees, loading }: { departments: Department[]; employees: Employee[]; loading: boolean }) { return <><PageHeader eyebrow="Organization" title="Departments" description="Understand how your team is structured." action={<button className="primary-button"><Plus size={17} /> Add department</button>} />{loading ? <Loading /> : <div className="department-grid">{departments.length === 0 ? <div className="panel empty-wide"><Empty title="No departments yet" text="Add departments to organize your employees." /></div> : departments.map((department) => { const members = employees.filter((employee) => employee.department_id === department.id); return <section className="department-card" key={department.id}><div className="department-accent" style={{ background: department.color }} /><div className="department-card-inner"><div className="department-icon" style={{ background: `${department.color}18`, color: department.color }}><ShieldCheck size={20} /></div><div className="department-card-title"><h2>{department.name}</h2><p>{department.description || 'No description added yet.'}</p></div><MoreHorizontal size={18} className="muted-icon" /><div className="department-footer"><strong>{members.length} {members.length === 1 ? 'person' : 'people'}</strong><div className="mini-avatars">{members.slice(0, 4).map((member) => <span key={member.id} className="avatar" style={{ background: member.avatar_color }}>{initials(member)}</span>)}</div></div></div></section>; })}</div>}</>; }
function Loading() { return <div className="loading"><span /><span /><span /></div>; }
function Empty({ title, text }: { title: string; text: string }) { return <div className="empty"><div className="empty-icon"><Users size={20} /></div><strong>{title}</strong><p>{text}</p></div>; }

function EmployeeForm({ departments, onClose, onSaved }: { departments: Department[]; onClose: () => void; onSaved: () => void }) { const [form, setForm] = useState({ first_name: '', last_name: '', email: '', job_title: '', department_id: departments[0]?.id ?? '', location: 'Remote', employment_type: 'Full-time' }); const [saving, setSaving] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); const { error } = await supabase.from('employees').insert(form); setSaving(false); if (error) return; onSaved(); }; return <Modal title="Add employee" onClose={onClose}><form onSubmit={submit} className="form-grid"><label>First name<input required value={form.first_name} onChange={(e) => setForm({ ...form, first_name: e.target.value })} /></label><label>Last name<input required value={form.last_name} onChange={(e) => setForm({ ...form, last_name: e.target.value })} /></label><label className="full">Work email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label><label className="full">Job title<input required value={form.job_title} onChange={(e) => setForm({ ...form, job_title: e.target.value })} /></label><label>Department<select value={form.department_id} onChange={(e) => setForm({ ...form, department_id: e.target.value })}><option value="">Unassigned</option>{departments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</select></label><label>Location<select value={form.location} onChange={(e) => setForm({ ...form, location: e.target.value })}><option>Remote</option><option>New York</option><option>London</option><option>San Francisco</option></select></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? 'Saving...' : 'Add employee'}</button></div></form></Modal>; }
function LeaveForm({ employees, onClose, onSaved }: { employees: Employee[]; onClose: () => void; onSaved: () => void }) { const [form, setForm] = useState({ employee_id: employees[0]?.id ?? '', leave_type: 'Annual leave', start_date: '', end_date: '', reason: '' }); const [saving, setSaving] = useState(false); const submit = async (event: FormEvent) => { event.preventDefault(); setSaving(true); const { error } = await supabase.from('leave_requests').insert(form); setSaving(false); if (error) return; onSaved(); }; return <Modal title="New time-off request" onClose={onClose}><form onSubmit={submit} className="form-grid"><label className="full">Employee<select required value={form.employee_id} onChange={(e) => setForm({ ...form, employee_id: e.target.value })}>{employees.map((employee) => <option key={employee.id} value={employee.id}>{employee.first_name} {employee.last_name}</option>)}</select></label><label>Leave type<select value={form.leave_type} onChange={(e) => setForm({ ...form, leave_type: e.target.value })}><option>Annual leave</option><option>Sick leave</option><option>Personal day</option><option>Parental leave</option></select></label><label>Start date<input required type="date" value={form.start_date} onChange={(e) => setForm({ ...form, start_date: e.target.value })} /></label><label>End date<input required type="date" value={form.end_date} onChange={(e) => setForm({ ...form, end_date: e.target.value })} /></label><label className="full">Reason<textarea value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} placeholder="Add context for this request" rows={3} /></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? 'Submitting...' : 'Submit request'}</button></div></form></Modal>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div className="modal-backdrop" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><div className="modal"><div className="modal-header"><h2>{title}</h2><button onClick={onClose}><X size={18} /></button></div>{children}</div></div>; }

export default App;
